### ISSUE TITLE
mamba is not supported with a custom condarc

### ISSUE THREAD

**Issue by xhochy** [conda-incubator/setup-miniconda#112]
Using `mamba` with a custom `.condarc` where `conda-forge` is listed in it as a channel doesn't work as https://github.com/conda-incubator/setup-miniconda/blob/1769c7ffe7723c9c5afb1f8fdd529afe5421ac8e/src/setup.ts#L740 only checks whether `conda-forge` is in the configuration of the action.

**Comment by bollwyvl** [comment]
Thanks for the report! Yes, already on #107 (which we're hoping to land in staged) we read (and keep around) the environment file, adding the effective config at any given point would let us get a more full picture of channels.

However, no doubt there will be other channels that _also_ include `mamba`... so maybe we just drop this check entirely.

Another thing: no doubt we'll have installers that result in a working `mamba` without doing a solve (either a `micromamba` #75 or just a `miniforge` #76 that has `mamba`). I think use of `mamba` still needs to be explicit, so if `mamba-version` is specified, we should just check whether the base env already has that (e.g. `mamba version`), rather than invoking the solver. Otherwise install.

**Comment by bollwyvl** [comment]
This bug is still present on `master`... it just fails much more quickly. I think we should just drop the warning, and hope folks know what they're doing, e.g. specifying channels correctly via condarc, env or action (gah).

**Comment by bollwyvl** [comment]
I think #133 fixes this, as it overhauled a lot of `mamba` stuff... i don't know what the time trade-off will be like between using `mamba-version` with the miniconda already on disk vs starting with `Mambaforge`, but at least it won't break _this_ way anymore...

**Comment by goanpeca** [comment]
@xhochy could you check running your CI with master `conda-incubator/setup-miniconda@master` and check if the problem is solved?

**Comment by xhochy** [comment]
Yes, this solved it but I ran into another issue as part of this: https://github.com/conda-incubator/setup-miniconda/issues/145
