### ISSUE TITLE
Error "The input line is too long" when running vcvarsall.bat in a conda environment

### ISSUE THREAD

**Issue by jdumas** [conda-incubator/setup-miniconda#136]
Hi there,

I'm facing a rather annoying issue trying to compile a C++ program in a conda environment. Usually, I would `call vcvarsall.bat` with right args to set up the development environment for Visual Studio. However, since I've updated from `goanpeca/setup-miniconda@v1` to `conda-incubator/setup-miniconda@v2` this no longer works and I encounter the following error:
```
The input line is too long.
The syntax of the command is incorrect.
```

You can see [here](https://github.com/MeshFEM/microstructures/pull/2/checks?check_run_id=1624655242) a run that illustrates the problem. I've tried several things, such as switching to Powershell (but still need to call `vcvarsall.bat` via cmd), or putting the whole line [into quotes](https://stackoverflow.com/questions/682799/what-to-do-with-the-input-line-is-too-long-error-message/3583282#3583282), but these did not work. When I comment out the conda env from the github action then things work again, so I think the combination of conda + vcvarsall.bat is exceeding some limit in an env variable somewhere...

Any idea what might have changes between v1 and v2 that would explain the error now?

**Comment by goanpeca** [comment]
Hi @jdumas thanks for the report!

We will look into it. @bollwyvl any ideas 🙃

**Comment by goanpeca** [comment]
@jdumas could you run your CI and print the content of %PATH% ?

**Comment by bollwyvl** [comment]
yuck, that's one of those files i tend to close my eyes when i see problems related to it.

We do explicitly `core.addPath` to `%CONDA%\condabin` (i didn't put it there, but it was probably for a good reason at the time), and then the shell integration adds a couple more things and `condabin` _again_, so yeah, we're costing you 22 needless characters. But, if indeed it's `%PATH%` length, it's really just "lucky" that _we_ broke it, as it's a trash heap on the hosted runners with something like...

<details>
<summary>this monstrosity...</summary>
<pre>
C:\aliyun-cli
C:\cf-cli
C:\hostedtoolcache\windows\go\1.14.13\x64\bin
C:\hostedtoolcache\windows\Python\3.7.9\x64
C:\hostedtoolcache\windows\Python\3.7.9\x64\Scripts
C:\hostedtoolcache\windows\Ruby\2.5.8\x64\bin
C:\hostedtoolcache\windows\stack\2.5.1\x64
C:\Miniconda\condabin
C:\Miniconda\condabin
C:\Miniconda\envs\foo
C:\Miniconda\envs\foo\bin
C:\Miniconda\envs\foo\Library\bin
C:\Miniconda\envs\foo\Library\mingw-w64\bin
C:\Miniconda\envs\foo\Library\usr\bin
C:\Miniconda\envs\foo\Scripts
C:\mysql-5.7.21-winx64\bin
C:\npm\prefix
C:\Program Files (x86)\GitHub CLI
C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin
C:\Program Files (x86)\Microsoft BizTalk Server
C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin
C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn
C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn
C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn
C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn
C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn
C:\Program Files (x86)\NSIS
C:\Program Files (x86)\pipx_bin
C:\Program Files (x86)\sbt\bin
C:\Program Files (x86)\sbt\bin
C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit
C:\Program Files\Amazon\AWSCLIV2
C:\Program Files\Amazon\AWSSAMCLI\bin
C:\Program Files\Amazon\SessionManagerPlugin\bin
C:\Program Files\CMake\bin
C:\Program Files\Docker
C:\Program Files\dotnet
C:\Program Files\dotnet
C:\Program Files\Git\bin
C:\Program Files\Git\cmd
C:\Program Files\Git\mingw64\bin
C:\Program Files\Git\usr\bin
C:\Program Files\Java\jdk8u275-b01\bin
C:\Program Files\Mercurial
C:\Program Files\Microsoft SDKs\Azure\Azure Dev Spaces CLI
C:\Program Files\Microsoft SDKs\Azure\Azure Dev Spaces CLI
C:\Program Files\Microsoft SDKs\Service Fabric\Tools\ServiceFabricLocalClusterManager
C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code
C:\Program Files\Microsoft SQL Server\130\Tools\Binn
C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn
C:\Program Files\Microsoft\Web Platform Installer
C:\Program Files\MongoDB\Server\4.4\bin
C:\Program Files\nodejs
C:\Program Files\OpenSSL\bin
C:\Program Files\PowerShell\7
C:\Program Files\R\R-4.0.3\bin\x64
C:\Program Files\TortoiseSVN\bin
C:\ProgramData\Chocolatey\bin
C:\ProgramData\chocolatey\lib\ghc.8.10.2.2\tools\ghc-8.10.2\bin
C:\ProgramData\chocolatey\lib\maven\apache-maven-3.6.3\bin
C:\ProgramData\chocolatey\lib\pulumi\tools\Pulumi\bin
C:\ProgramData\kind
C:\Rust\.cargo\bin
C:\SeleniumWebDrivers\ChromeDriver
C:\SeleniumWebDrivers\EdgeDriver
C:\SeleniumWebDrivers\GeckoDriver
C:\Strawberry\c\bin
C:\Strawberry\perl\bin
C:\Strawberry\perl\site\bin
c:\tools\php
C:\Users\runneradmin\.dotnet\tools
C:\Users\runneradmin\AppData\Local\Microsoft\WindowsApps
C:\vcpkg
C:\windows
C:\windows\system32
C:\windows\System32\OpenSSH
C:\windows\System32\Wbem
C:\windows\System32\WindowsPowerShell\v1.0
</pre>
</details>

You really need perlANDperlANDhaskellANDrustANDtortoisesvnANDchocolatelyANDseleniumANDmongoANDsqlserverANDsqlserverANDsqlserver?

But anyhow: on other systems where I've been blessed with the opportunity to debug ms build tools, I usually try to install to the shortest path possible, like `md c:\mc3 && conda create --prefix c:\mc3`. 

Taking that idea further, the most direct path _this_ repo could take: detect whether `activate-environment` is an absolute path, and then use `--prefix` instead of `--name` when creating. This would save about 100 characters... about the same bang for your buck as removing that behemoth `ServiceFabricLocalClusterManager` or 2 `Microsoft SQL Server`s in a wrapper script (or some environment file stuff)... but it _would_ have other advantages, as `--prefix` is accepted by a lot of conda tools.

We could _also_ offer an action input for where a custom mini* installer is actually installed, but now we're probably getting to diminishing marginal returns (`c:\miniconda` is already _pretty_ short)... but we can't move the aging, but still very functional, and _very_ fast-to-start bundled one.

**Comment by jdumas** [comment]
Thanks guys. So after closer inspection, it turns out this was really a compounding effect adding to the `PATH` variable. I had another step where I install `sccache` via `scoop`, and I had the good idea of doing the following:
```
echo "${env:PATH}" >> ${env:GITHUB_PATH}
```

Which obviously doubled the length of the `%PATH%` variable... Anyhow, [here](https://github.com/MeshFEM/microstructures/pull/2/checks?check_run_id=1624870297) is a failed run showing the PATH with the duplicated entries, and [here](https://github.com/MeshFEM/microstructures/pull/2/checks?check_run_id=1624894559) is another run where I don't double the size of the `%PATH%` variable.

Guess I was just lucky this didn't bite me before, but I'm glad I have a fix now. Feel free to close the issue!

**Comment by goanpeca** [comment]
Great to hear you found a workaround :) !

**Comment by bollwyvl** [comment]
Huzzah! Maybe we add the prefix thingy _anyway_, as eventually something is
going to need those extra ten characters to not break for _other_ reasons
on windows.

**Comment by goanpeca** [comment]
>%CONDA%\condabin 

Cannot recall now... newer versions of conda use `condabin` as the place to put the execs, whereas older (bundled in GH images) versions of conda use `%CONDA%\bin` ... 

I cannot recall the exact why now 😆

**Comment by bollwyvl** [comment]
i'll try turning it off on #137...

**Comment by jaimergp** [comment]
I think we need that dir in PATH for `mamba`
