### ISSUE TITLE
Environment file with pip dependency file

### ISSUE THREAD

**Issue by mloubout** [conda-incubator/setup-miniconda#162]
It seems like the latest `v2.1.0` has broken the processing of custom environment file with 

```
  - pip:
    - -r file:requirements.txt
```

That now seems to look for it at a non-existing location:

```
  Installing pip dependencies: ...working... Ran pip subprocess with arguments:
  ['/usr/share/miniconda/envs/devito/bin/python', '-m', 'pip', 'install', '-U', '-r', '/tmp/condaenv.zimdqc7e.requirements.txt']
  Pip subprocess output:
  
  failed
  Warning: Pip subprocess error:
  ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
```

Is this supposed to not be supported anymore and what's the proposed fix?

**Comment by bollwyvl** [comment]
Yep, suppose that will happen when you specify `python-version`, which applies a patch. This was done to avoid doing multiple conda solves

We probably need to:
- generate a patched file _in-place_ rather than in `/tmp` to support this case
- add a test

Will get to this when I get a chance... but that's not going to be until at this evening at the earliest.

Your quick bets are to:
- don't use `python-version`
  - ensure your `environment.yml` specifies python (`sed` can help)
- continue to use `python-version`
  - patch your `-r ` to points at an absolute path or
  - do a dedicated step of `pip install -r requirements.txt`

**Comment by mloubout** [comment]
Thanks for the quick answer. 

>do a dedicated step of pip install -r requirements.txt

Yes that works but need yet another yaml file we trying to avoid, may have to do it in the meantime.

> ensure your environment.yml specifies python

We'd like to avoid that too so will fall back to above.

Checking without `python-version` thanks.

**Comment by mloubout** [comment]
Removing the python version did the trick (for some extremely lucky unknown reason our CI did not break with the default 3.9 we're not supposed to support).

Closing

**Comment by bollwyvl** [comment]
> yet another yaml file 

It wouldn't be another _file_, just a step, e.g.

```
steps:
- use: conda-incubator/setup-miniconda@v2
- run: pip install -r requirements.txt
```

Glad you got sorted, we'll try to figure out some way to fix it up that doesn't break _other_ peoples' stuff...
