### ISSUE TITLE
setup-miniconda step failing with error 'error in simpleeval setup command: use_2to3 is invalid.'

### ISSUE THREAD

**Issue by dcaribou** [conda-incubator/setup-miniconda#195]
One of the workflows where I use the setup-miniconda@v2 step started failing on `2021-09-13` with the error

> error in simpleeval setup command: use_2to3 is invalid.

Link to the full log [here](https://github.com/dcaribou/transfermarkt-datasets/runs/3583787729).

I am able to create the environment locally with the same `environment.yml` file without issue with the command
```
> conda env create -f environment.yml
```

**Comment by jaimergp** [comment]
Looks like pip is trying to install `simpleeval` from source (it might be needed by one of your packages under the `pip:` category). This is probably not an issue with the GH Action itself, but a change in the metadata of the packages involved (not necessarily the ones you specified, but also their dependencies).

You are also pinning versions heavily, which might restrict which versions it can try. I would install `pandas` from conda instead of pip, though; that's a heavy dependency and it will work better if handled in the conda world.

**Comment by jaimergp** [comment]
Maybe you can also add `simpleeval` to the conda requirements. It's [available](https://anaconda.org/conda-forge/simpleeval) on conda-forge already. That way, `pip` will detect it as installed by the time it runs. But again, the less packages you install with pip, the better.

**Comment by dcaribou** [comment]
Hey @jaimergp. This actually happened with a previous version of the environment.yml file where the `pandas` was listed as a conda dependency instead of pip. That's why I tried by listing pandas as a pip dependency. [Here's](https://github.com/dcaribou/transfermarkt-datasets/runs/3583680547) the attempt. 

I'll try your suggestion of adding `simpleeval` and `pandas` as conda deps and let you know.

**Comment by jaimergp** [comment]
Yea, I don't know who's pulling `simpleeval` in, but now we know it's _not_ pandas. I think adding `simpleeval` to the conda requirements should fix it! 🤞

**Comment by dcaribou** [comment]
Adding `simpleeval` as a conda dep [did it](https://github.com/dcaribou/transfermarkt-datasets/actions/runs/1228895849). Thanks @jaimergp!
You are right, this is not an issue with the GH Action. I'm closing this.

**Comment by jezdez** [comment]
FWIW when looking at the log you can find that frictionless has a dependency for simpleeval. The bug in question is triggered by setuptools 58 dropping support for use_2to3: https://setuptools.readthedocs.io/en/latest/history.html#v58-0-0
