### ISSUE TITLE
Cannot use simple provider

### ISSUE THREAD

**Issue by dzelge** [conda-incubator/setup-miniconda#211]
Hi There,
we are interested in using the env provider `simple` from `ensureSimple`. However, we don't seem to find the right configuration in order to use that mode. We are interested because `simple` uses `conda create` instead of `conda update` which messes up our dependencies versions.

Thanks heaps

**Comment by jaimergp** [comment]
The "simplest" way I can possibly think of right now is to:

* create your own `constructor` installer, upload it and pass the URL to the action
* pin your environment file in a stricter way

**Comment by dzelge** [comment]
Thanks heaps for the answer. I'll try that. I was wondering, though, why I cannot use this one:

```ts
export const ensureSimple: types.IEnvProvider = {
  label: "conda create (simple)",
  provides: async (inputs, options) => {
    return !(
      options.envSpec?.explicit?.length ||
      Object.keys(options.envSpec?.yaml || {}).length
    );
  },
  condaArgs: async (inputs, options) => {
    const args = ["create", ...conda.envCommandFlag(inputs)];

    if (inputs.pythonVersion) {
      const spec = utils.makeSpec("python", inputs.pythonVersion);
      core.info(`Adding spec: ${spec}`);
      args.push(spec);
    }

    return args;
  },
};
```

**Comment by bollwyvl** [comment]
The simple only works with things crafted with "conda-lock" or "conda list
--explicit" and will contain the line @EXPLICIT.

There's some docs about them here:

https://github.com/conda-incubator/setup-miniconda#example-7-lockfiles

The reason for the name "simple" is that it doesn't support very many
options, including channels, and are not affected by the environment
patching for python, which we can't get rid of for historical reasons. It
is also about as fast as conda/mamba can get on a cold cache.

Otherwise it is assumed the environment-file is a yaml to be used by "conda
env," and seems to work for many projects' needs.

What does your file look like, and how many bells and whistles are you
trying to set in coordination with it? We usually try to warn and fail
really if things are grossly misconfigured.

**Comment by dzelge** [comment]
I understand. 
Thanks for answering anyway. Very much appreciated.
H
