### ISSUE TITLE
Turn on branch protection for the repo

### ISSUE THREAD

**Issue by joamatab** [conda-incubator/setup-miniconda#271]
Hi, I love this GitHub action

How could we turn branch protection for the repo?

This would make it more secure and allow us to use it within our organization

**Comment by mmaraya** [comment]
Here's some context on branch protection if that helps: https://github.com/ossf/scorecard/blob/main/docs/checks.md#branch-protection.

**Comment by mattwthompson** [comment]
I'm in support of adding a minimal branch protecting; in other orgs I've been happy with basic rules like "1 approving review"

**Comment by dbast** [comment]
+1  This would be now possible as the RELEASE.md file was changed via https://github.com/conda-incubator/setup-miniconda/pull/309 to not require pushing directly to main anymore.

So best thing (that how many other projects operate):
* allow changes in main branch only via PR
* no exception to admins, by enabling "Do not allow bypassing the above settings" in the protection rule
* Require 1 review before merging

@joamatab no matter how protected branches are, things in a git repo are still mutable if only referenced by tag/branch name ... best security is provided by referencing the action via SHA1 and update the reference via dependabot/renovate as explained [here](https://github.blog/changelog/2022-10-31-dependabot-now-updates-comments-in-github-actions-workflows-referencing-action-versions/) ... like `conda-incubator/setup-miniconda@9f54435e0e72c53962ee863144e47a4b094bfd35 # v2.3.0` instead of `conda-incubator/setup-miniconda@v2.3.0`.

**Comment by goanpeca** [comment]
Just added the following:

<img width="856" alt="Screenshot 2023-11-23 at 12 02 42 PM" src="https://github.com/conda-incubator/setup-miniconda/assets/3627835/a3990513-366b-4428-83fb-06bba7fd2650">
<img width="831" alt="Screenshot 2023-11-23 at 12 02 36 PM" src="https://github.com/conda-incubator/setup-miniconda/assets/3627835/2f7c535f-8ab5-4db4-b1f9-f1811496114c">
<img width="831" alt="Screenshot 2023-11-23 at 12 02 29 PM" src="https://github.com/conda-incubator/setup-miniconda/assets/3627835/e4672c03-e584-467c-98df-3b4590e6de57">

Anything else I missed @dbast ?

**Comment by dbast** [comment]
@goanpeca Looks good... requiring status checks to pass can cause some pain if those are renamed etc... could be better that the maintainer group checks that before merge instead of putting that into the settings... but this should be also fine if no status checks is selected in the settings list.

**Comment by goanpeca** [comment]
Removed the status checks one. Thanks

Closing this one!
