### ISSUE TITLE
"Warning - a newer version of conda exists" - logged as a warning on Windows

### ISSUE THREAD

**Issue by aldanor** [conda-incubator/setup-miniconda#58]
Below a snippet of the log, installing conda on `windows-latest` with this config:

```yaml
with:
  auto-update-environment: false
  activate-environment: testenv
```

If you notice the `##[warning]` below, I think that's what's causing the warning to get logged and reported as an annotation in actions ui? Interestingly, it does only happen on windows runners.

Is there any way to suppress that?

```
:: --------------------------------------------------------------------------- 

# Create test environment...
############################

C:\windows\system32\cmd.exe /D /S /C "C:\Miniconda\condabin\conda.bat create --name testenv"
Collecting package metadata: ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Miniconda\envs\testenv

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
##[warning]

==> WARNING: A newer version of conda exists. <==
  current version: 4.6.14
  latest version: 4.8.3

Please update conda by running

    $ conda update -n base -c defaults conda

==> WARNING: A newer version of conda exists. <==
  current version: 4.6.14
```

**Comment by goanpeca** [comment]
Hi @aldanor, thanks for the report.

I will take a look at it.

Cheers!

**Comment by aldanor** [comment]
@goanpeca Any thoughts?

Here's how it shows up, as an example: https://github.com/aldanor/hdf5-rust/actions/runs/191675608

**Comment by aldanor** [comment]
Is it this line if I understand correctly?

https://github.com/goanpeca/setup-miniconda/blob/89d2ae960c9c349ae79f886c611cc3559a1319d1/src/setup.ts#L81

**Comment by adriangb** [comment]
I'm seeing this on `ubuntu` runners as well: https://github.com/adriangb/geopandas/actions/runs/222583237

**Comment by goanpeca** [comment]
Although the are harmless, I agree they are annoying. I won't be able to look into this for some weeks.

**Comment by weiji14** [comment]
One thing I've noticed is that the Github Actions windows-latest runner uses an old version of miniconda ([4.6.14 released April 2019](https://github.com/conda/conda/releases/tag/4.6.14)) see https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md#package-management, compared to ubuntu/macOS which is currently at [4.8.3](https://github.com/conda/conda/releases/tag/4.8.3). Is it worth pushing on upstream at https://github.com/actions/virtual-environments to get a newer miniconda version on Windows, since conda [4.7.0](https://github.com/conda/conda/releases/tag/4.7.0) and above comes with various speed improvements and enhancements?

**Comment by goanpeca** [comment]
That sounds like a good idea. Maybe add to the issue linked so others can go and bump a 👍

**Comment by MaxGhenis** [comment]
Is this issue for Windows only? As in https://github.com/conda-incubator/setup-miniconda/issues/58#issuecomment-679363062, I'm also seeing it on Ubuntu. Could it be renamed if for both? Or I can open a new issue for Ubuntu otherwise.

I thought that
```
with:
  miniconda-version: "latest"
```
would fix it, but it does not. (What does that statement do?)

**Comment by goanpeca** [comment]
When installing the latest conda, conda itself might raise the warning.

**Comment by weiji14** [comment]
> That sounds like a good idea. Maybe add to the issue linked so others can go and bump a +1

Cool, feature request opened at https://github.com/actions/virtual-environments/issues/1580, let's all go and add our upvotes! Or if someone wants to submit a PR, go for it too!

> Is this issue for Windows only? As in [#58 (comment)](https://github.com/conda-incubator/setup-miniconda/issues/58#issuecomment-679363062), I'm also seeing it on Ubuntu. Could it be renamed if for both? Or I can open a new issue for Ubuntu otherwise.
>
> I thought that
> 
> ```
> with:
>   miniconda-version: "latest"
> ```
> 
> would fix it, but it does not. (What does that statement do?)

The reason the warning exists for Ubuntu too is because the latest conda version is 4.8.4, but only 4.8.3 installers are available (see https://repo.anaconda.com/miniconda/). The 'miniconda-version: "latest"' is only able to pull down the 'Miniconda3-latest-Linux-x86_64.sh' installer, which is at 4.8.3 right now.

**Comment by bollwyvl** [comment]
This will be a problem every time a new installer is released, it's likely not worth trying to get multiple upstreams to synchronize. 

Some possible, not mutually-exclusive thoughts while working on clobbering _other_ errors on #79:
- write out a "bootstrap" `~/.condarc` with `notify_outdated_conda: false` when running the installer, delete after
  - subsequent uses of `conda` would still warn 
- move the config file copying to before the installer run
  - if folks don't like the errors, [suppress it](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-conda.html#suppressing-warning-message-about-updating-conda)
- add a `notify-outdated-conda` to `actions.yml`
  - this might be the only config change folks might need to make for simple cases, so could be convenient

**Comment by bollwyvl** [comment]
I guess since we're looking to get this into #79, my preference would be for the first choice, e.g. bootstrap condarc during installer/conda upgrade... but will entertain the other options.

**Comment by bollwyvl** [comment]
#79 has added the bootstrap approach. I decided to _not_ clean it up, as it will get overwritten if a `condarc-file` is specified. Otherwise, I just don't think folk will care enough to have exactly the hottest version of conda.
