### ISSUE TITLE
Cannot uninstall/update package (via pip) on Windows

### ISSUE THREAD

**Issue by loikein** [conda-incubator/setup-miniconda#88]
The full checks result is here: https://github.com/OpenSourceEconomics/econsa/pull/77/checks?check_run_id=1336112538

### System setup

Environment:

```yaml
  - pip:
    - isort
    - pytest-stress
    - pytest-randomly
    - black>=20.8b0
    - black-nb
    - flake8-nb
    - numpydoc
    - cairosvg
    - sphinxcontrib-svg2pdfconverter[CairoSVG]
```

Workflow:

```yaml
jobs:
  run-tests:
    name: Run tests for ${{ matrix.os }} on ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ['3.7']

    steps:
    - uses: actions/checkout@v2

    - uses: goanpeca/setup-miniconda@v1
      with:
          auto-update-conda: false
          activate-environment: econsa
          environment-file: environment.yml
          python-version: ${{ matrix.python-version }}
```

### Error message (on Windows)

```text
Installing collected packages: isort, pytest-stress, pytest-randomly, black, black-nb, flake8-nb, numpydoc, cairocffi, tinycss2, cssselect2, cairosvg, sphinxcontrib-svg2pdfconverter

  Attempting uninstall: black

    Found existing installation: black 19.10b0

    Uninstalling black-19.10b0:

      Successfully uninstalled black-19.10b0

Warning: Pip subprocess error:
ERROR: Could not install packages due to an EnvironmentError: [WinError 5] Access is denied: 'C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\pip-uninstall-vxstmnu2\\black.exe'

Consider using the `--user` option or check the permissions.


CondaEnvException: Pip failed


Error: The process 'C:\Miniconda\condabin\conda.bat' failed with exit code 1
```

### Expected result (on Linux)

```text
 Installing collected packages: isort, pytest-stress, pytest-randomly, black, black-nb, flake8-nb, numpydoc, tinycss2, cssselect2, cairocffi, cairosvg, sphinxcontrib-svg2pdfconverter
  Attempting uninstall: black
    Found existing installation: black 19.10b0
    Uninstalling black-19.10b0:
      Successfully uninstalled black-19.10b0
Successfully installed black-20.8b1 black-nb-0.3.0 cairocffi-1.2.0 cairosvg-2.5.0 cssselect2-0.4.1 flake8-nb-0.2.5 isort-5.6.4 numpydoc-1.1.0 pytest-randomly-3.4.1 pytest-stress-1.0.1 sphinxcontrib-svg2pdfconverter-1.1.0 tinycss2-1.1.0
```

**Comment by bollwyvl** [comment]
Windows permissions are a nasty thing. Can the fail be isolated on a real windows box?

While one _can_ install a number of those things with `pip`, usually a build will work more predictably (or fail faster, and _arguably_ more usefully) when _mostly_ sourced from `conda`(`-forge`). Mostly, this is due to also fulfilling any transient dependencies, and be a bit more thoughtful about windows issues, as many projects just don't test on windows, or don't test their built artifacts.

Indeed, it looks like installing `black` from conda [gets you sorted](https://github.com/OpenSourceEconomics/econsa/runs/1336201559). Of the remaining, looks like the following are available from (at least) `conda-forge`:
- `cairosvg`
- `isort`
- `numpydoc`

From a performance perspective, without knowing much about your build (or what else you do with that environment file):
- if you aren't using/testing `qt`, specifying `matplotlib-base` will (probably) save a few hundred megabytes
- similarly, the `jupyter` package is a metapackage that hauls in half the universe (including `qt`)... 
  - having specified `jupyterlab`, it will bring in most of the stuff you want... 
  - if you're actually using `ipywidgets`, it is reasonable to name that directly

**Comment by loikein** [comment]
Thank you very much for your detailed reply. I will certainly try out your advice.

Unfortunately, most of my team members use Mac or Linux, so CI is currently our only method to test on Windows. If you take a look at the workflow file, you will see that it's not the most heavily tested platform…

Anyways, many thanks again!
